# Generated by Django 2.0 on 2017-12-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='things',
        ),
    ]
