# Generated by Django 2.0 on 2017-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_delete_things'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
